CREATE TABLE PATIENT
{
	numSS INT PRIMARY KEY NOT NULL,
	nomP VARCHAR(100),
    prenomP VARCHAR(100),
    sexe VARCHAR (100),
    dateNaiss DATE,
    numRPPS int,
    FOREIGN KEY(numRPPS) REFERENCES MEDECIN(numRPPS),
	
    
}


CREATE TABLE MEDECIN
{
	numRPPS INT PRIMARY KEY NOT NULL,
	nomM VARCHAR(100),
	prenomM VARCHAR(100),
	specialite VARCHAR(100),
	ville VARCHAR(100),
	adresse VARCHAR(250),

}

CREATE TABLE CONSULTE
{
	numRPPS INT,
	numSS INT,
	dateSS DATE,
	diagnostic VARCHAR(200),
	numOrd INT,
	FOREIGN KEY(numRPPS) REFERENCES MEDECIN(numRPPS),
	FOREIGN KEY(numSS) REFERENCES PATIENT(numSS),

}